trial_name: stackcube_ppo_default
log_dir: logs

env:
    name: StackCube-v1
    # number of parallel envs
    n_env_procs: 16
    # observation mode
    obs_mode: "state"
    # control mode/action mode
    act_mode: pd_ee_delta_pose
    seed: 42

train:
    # max number of steps in one training episode
    max_eps_steps: 200
    # total number of training steps
    total_steps: 25000000
    # number of steps to run before each network update
    rollout_steps: 5000
    # batch size in each update of the PPO surrogate loss
    batch_size: 64
    # reward discounting factor
    gamma: 0.99
    lr: 0.0003

model_name: PPO
net_arch: [256, 256]
model_kwargs:
    verbose: 1
    # max KL div btw old/new policy in one update
    # target_kl: None
    ent_coef: 0
    n_epochs: 10
    n_steps: 2048

eval:
    # evaluation frequency, measured by the number of network updates
    eval_freq: 10
    # number of episodes to run in each evaluation
    n_eval_episodes: 10
